Poc/setup game
angelmiguelmontalvo/finalProject-2020-q3 pull request #12
Opened 2020-08-22 04:17 UTC by angelmiguelmontalvo

2020-08-22 22:35 UTC, lufercc commented
@angelmiguelmontalvo you trying to push into Master.

2020-08-23 01:30 UTC, jccolina requested changes

2020-08-23 01:30 UTC, jccolina commented on finalProject-2020-q3/code/King.cs
> +            resultList.SetList(cellList.Where(cell => cell.IsEmpty() == false).ToList());
@angelmiguelmontalvo I think is necessary to add the Color validation "&& cell.piece.Color != Color" to line 42

2020-08-23 01:30 UTC, jccolina commented on finalProject-2020-q3/code/Knight.cs
> +            resultList.SetList(cellList.Where(cell => cell.IsEmpty() == false).ToList());
@angelmiguelmontalvo I think is necessary to add the Color validation "&& cell.piece.Color != Color"

2020-08-23 01:30 UTC, jccolina commented on finalProject-2020-q3/code/Rook.cs
> +            resultList.SetList(cellList.Where(cell => cell.IsEmpty() == false).ToList());
@angelmiguelmontalvo I think is necessary to add the Color validation "&& cell.piece.Color != Color"

2020-08-23 01:30 UTC, jccolina commented on finalProject-2020-q3/game/Game.cs
> +			result = Regex.IsMatch(command, SelectRegex);
@angelmiguelmontalvo I think here we could re-use the IsMovement and IsSelect validation something like:
if(IsSelectCommand(command)) 
{return true}
else{
return IsMovementCommand(command);
}

2020-08-23 02:23 UTC, jccolina approved these changes

2020-08-23 02:24 UTC, merged